// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalRRHHFZ.Infrastructure.Data;

#nullable disable

namespace PortalRRHHFZ.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260622200720_AddSolicitudesRequisiciones")]
    partial class AddSolicitudesRequisiciones
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.Alerta", b =>
                {
                    b.Property<int>("AlertaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlertaId"));

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DocumentoColaboradorId")
                        .HasColumnType("int");

                    b.Property<string>("EstadoAlerta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaGeneracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaGestion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GestionadaPor")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ObservacionGestion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TipoAlerta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AlertaId");

                    b.HasIndex("ColaboradorId");

                    b.HasIndex("DocumentoColaboradorId");

                    b.HasIndex("GestionadaPor");

                    b.HasIndex("TipoAlerta", "ColaboradorId", "DocumentoColaboradorId", "FechaVencimiento")
                        .IsUnique()
                        .HasFilter("[DocumentoColaboradorId] IS NOT NULL");

                    b.ToTable("Alertas", (string)null);
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.Cargo", b =>
                {
                    b.Property<int>("CargoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CargoId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CargoId");

                    b.HasIndex("DepartamentoId");

                    b.ToTable("Cargos", (string)null);
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.Colaborador", b =>
                {
                    b.Property<int>("ColaboradorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColaboradorId"));

                    b.Property<int>("CargoId")
                        .HasColumnType("int");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("EstatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaSalida")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimientoCedula")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimientoContrato")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimientoLicencia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimientoPeriodoProbatorio")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GastosRepresentacion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("JefeInmediatoId")
                        .HasColumnType("int");

                    b.Property<int?>("MotivoSalidaId")
                        .HasColumnType("int");

                    b.Property<string>("NoEmpleado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroLicencia")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PrimerApellido")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PrimerNombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SegundoApellido")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("SegundoNombre")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("SeguroSocial")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sexo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TieneLicencia")
                        .HasColumnType("bit");

                    b.Property<int>("TipoContratoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoLicencia")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime?>("UltimaVacacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Vacante")
                        .HasColumnType("bit");

                    b.Property<decimal>("Viaticos")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ColaboradorId");

                    b.HasIndex("CargoId");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("EstatusId");

                    b.HasIndex("JefeInmediatoId");

                    b.HasIndex("MotivoSalidaId");

                    b.HasIndex("NoEmpleado")
                        .IsUnique();

                    b.HasIndex("TipoContratoId");

                    b.ToTable("Colaboradores", (string)null);
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.Departamento", b =>
                {
                    b.Property<int>("DepartamentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartamentoId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartamentoId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Departamentos", (string)null);
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.DocumentoColaborador", b =>
                {
                    b.Property<int>("DocumentoColaboradorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentoColaboradorId"));

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RutaArchivo")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<int>("SubidoPor")
                        .HasColumnType("int");

                    b.Property<bool>("TieneVencimiento")
                        .HasColumnType("bit");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentoColaboradorId");

                    b.HasIndex("ColaboradorId");

                    b.HasIndex("SubidoPor");

                    b.HasIndex("TipoDocumentoId");

                    b.ToTable("DocumentosColaborador", (string)null);
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.Empresa", b =>
                {
                    b.Property<int>("EmpresaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpresaId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Ruc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmpresaId");

                    b.ToTable("Empresas", (string)null);
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.EstatusColaborador", b =>
                {
                    b.Property<int>("EstatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstatusId"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EstatusId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("EstatusColaborador", (string)null);

                    b.HasData(
                        new
                        {
                            EstatusId = 1,
                            Codigo = "A",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Nombre = "Activo"
                        },
                        new
                        {
                            EstatusId = 2,
                            Codigo = "C",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Nombre = "Cesante"
                        },
                        new
                        {
                            EstatusId = 3,
                            Codigo = "V",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Nombre = "Vacaciones"
                        },
                        new
                        {
                            EstatusId = 4,
                            Codigo = "S",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Nombre = "Servicio"
                        },
                        new
                        {
                            EstatusId = 5,
                            Codigo = "SU",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Nombre = "Suspendido"
                        });
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.HistorialColaborador", b =>
                {
                    b.Property<int>("HistorialColaboradorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistorialColaboradorId"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Campo")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Observacion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("ValorAnterior")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ValorNuevo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("HistorialColaboradorId");

                    b.HasIndex("ColaboradorId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistorialColaborador", (string)null);
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.MotivoSalida", b =>
                {
                    b.Property<int>("MotivoSalidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MotivoSalidaId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MotivoSalidaId");

                    b.ToTable("MotivosSalida", (string)null);

                    b.HasData(
                        new
                        {
                            MotivoSalidaId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Nombre = "Renuncia"
                        },
                        new
                        {
                            MotivoSalidaId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Nombre = "Despido"
                        },
                        new
                        {
                            MotivoSalidaId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Nombre = "Mutuo acuerdo"
                        },
                        new
                        {
                            MotivoSalidaId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Nombre = "Finalizacion de contrato"
                        },
                        new
                        {
                            MotivoSalidaId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Nombre = "No aplica"
                        });
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.RequisicionPersonal", b =>
                {
                    b.Property<int>("RequisicionPersonalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequisicionPersonalId"));

                    b.Property<int?>("AniosExperiencia")
                        .HasColumnType("int");

                    b.Property<string>("AreaSectorExperiencia")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("AutorizadoPorTexto")
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("CaracteristicasPersonales")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("CargoSolicitado")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("CentroTrabajo")
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<int?>("ColaboradorReemplazadoId")
                        .HasColumnType("int");

                    b.Property<string>("ConocimientosTecnicos")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ConocimientosValorados")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartamentoSolicitadoId")
                        .HasColumnType("int");

                    b.Property<string>("DependenciaJerarquica")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("EdadMaxima")
                        .HasColumnType("int");

                    b.Property<int?>("EdadMinima")
                        .HasColumnType("int");

                    b.Property<string>("EquipoACargo")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("EsPosicionNueva")
                        .HasColumnType("bit");

                    b.Property<bool>("EsReemplazo")
                        .HasColumnType("bit");

                    b.Property<string>("ExperienciaValorable")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("FechaAperturaProceso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaAutorizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEntregaCandidatos")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormacionComplementaria")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FormacionRequerida")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FuncionesEspecificas")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("FuncionesExperiencia")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<decimal?>("GastoRepresentacion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IdiomaNivel")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NombrePersonaReemplazada")
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<int>("NumeroPlazas")
                        .HasColumnType("int");

                    b.Property<string>("OtrosConceptos")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PeriodoPrueba")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("PrincipalesResponsabilidades")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<decimal?>("Salario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SalarioVariable")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SexoPreferido")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("SolicitadoPorTexto")
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("int");

                    b.Property<int?>("TipoContratoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequisicionPersonalId");

                    b.HasIndex("ColaboradorReemplazadoId");

                    b.HasIndex("DepartamentoSolicitadoId");

                    b.HasIndex("SolicitudId")
                        .IsUnique();

                    b.HasIndex("TipoContratoId");

                    b.ToTable("RequisicionesPersonal", (string)null);
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RolId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Acceso completo a V1",
                            IsActive = true,
                            Nombre = "Admin"
                        },
                        new
                        {
                            RolId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Gestion operativa de RRHH V1",
                            IsActive = true,
                            Nombre = "RRHH"
                        },
                        new
                        {
                            RolId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Reservado para fases futuras",
                            IsActive = true,
                            Nombre = "Supervisor"
                        },
                        new
                        {
                            RolId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Descripcion = "Reservado para fases futuras",
                            IsActive = true,
                            Nombre = "Consulta"
                        });
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.Solicitud", b =>
                {
                    b.Property<int>("SolicitudId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SolicitudId"));

                    b.Property<int?>("CargoId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoSolicitud")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("ColaboradorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaEfectiva")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Justificacion")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("SolicitanteUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("TipoSolicitud")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SolicitudId");

                    b.HasIndex("CargoId");

                    b.HasIndex("CodigoSolicitud")
                        .IsUnique();

                    b.HasIndex("ColaboradorId");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("SolicitanteUsuarioId");

                    b.HasIndex("TipoSolicitud", "Estado");

                    b.ToTable("Solicitudes", (string)null);
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.SolicitudAprobacion", b =>
                {
                    b.Property<int>("SolicitudAprobacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SolicitudAprobacionId"));

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Etapa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaDecision")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("RolAprobador")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioAprobadorId")
                        .HasColumnType("int");

                    b.HasKey("SolicitudAprobacionId");

                    b.HasIndex("UsuarioAprobadorId");

                    b.HasIndex("SolicitudId", "Orden")
                        .IsUnique();

                    b.ToTable("SolicitudAprobaciones", (string)null);
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.SolicitudHistorial", b =>
                {
                    b.Property<int>("SolicitudHistorialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SolicitudHistorialId"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Comentario")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EstadoAnterior")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EstadoNuevo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("SolicitudHistorialId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("SolicitudId", "Fecha");

                    b.ToTable("SolicitudHistorial", (string)null);
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.TipoContrato", b =>
                {
                    b.Property<int>("TipoContratoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoContratoId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("RequiereFechaVencimiento")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoContratoId");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposContrato", (string)null);

                    b.HasData(
                        new
                        {
                            TipoContratoId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Nombre = "Permanente",
                            RequiereFechaVencimiento = false
                        },
                        new
                        {
                            TipoContratoId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Nombre = "Eventual",
                            RequiereFechaVencimiento = true
                        });
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.TipoDocumento", b =>
                {
                    b.Property<int>("TipoDocumentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoDocumentoId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("TieneVencimientoSugerido")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoDocumentoId");

                    b.ToTable("TiposDocumento", (string)null);

                    b.HasData(
                        new
                        {
                            TipoDocumentoId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Nombre = "Cedula",
                            TieneVencimientoSugerido = true
                        },
                        new
                        {
                            TipoDocumentoId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Nombre = "Contrato",
                            TieneVencimientoSugerido = true
                        },
                        new
                        {
                            TipoDocumentoId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Nombre = "Carnet",
                            TieneVencimientoSugerido = true
                        },
                        new
                        {
                            TipoDocumentoId = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Nombre = "Licencia",
                            TieneVencimientoSugerido = true
                        },
                        new
                        {
                            TipoDocumentoId = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Nombre = "Certificado",
                            TieneVencimientoSugerido = true
                        },
                        new
                        {
                            TipoDocumentoId = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Nombre = "Evaluacion",
                            TieneVencimientoSugerido = false
                        },
                        new
                        {
                            TipoDocumentoId = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Nombre = "Carta disciplinaria",
                            TieneVencimientoSugerido = false
                        },
                        new
                        {
                            TipoDocumentoId = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Nombre = "Comprobante",
                            TieneVencimientoSugerido = false
                        },
                        new
                        {
                            TipoDocumentoId = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Nombre = "CV",
                            TieneVencimientoSugerido = false
                        },
                        new
                        {
                            TipoDocumentoId = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Nombre = "Otro",
                            TieneVencimientoSugerido = false
                        });
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.Alerta", b =>
                {
                    b.HasOne("PortalRRHHFZ.Domain.Entities.Colaborador", "Colaborador")
                        .WithMany("Alertas")
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortalRRHHFZ.Domain.Entities.DocumentoColaborador", "DocumentoColaborador")
                        .WithMany("Alertas")
                        .HasForeignKey("DocumentoColaboradorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PortalRRHHFZ.Domain.Entities.Usuario", "UsuarioGestiono")
                        .WithMany("AlertasGestionadas")
                        .HasForeignKey("GestionadaPor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Colaborador");

                    b.Navigation("DocumentoColaborador");

                    b.Navigation("UsuarioGestiono");
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.Cargo", b =>
                {
                    b.HasOne("PortalRRHHFZ.Domain.Entities.Departamento", "Departamento")
                        .WithMany("Cargos")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.Colaborador", b =>
                {
                    b.HasOne("PortalRRHHFZ.Domain.Entities.Cargo", "Cargo")
                        .WithMany("Colaboradores")
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortalRRHHFZ.Domain.Entities.Departamento", "Departamento")
                        .WithMany("Colaboradores")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortalRRHHFZ.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Colaboradores")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortalRRHHFZ.Domain.Entities.EstatusColaborador", "Estatus")
                        .WithMany("Colaboradores")
                        .HasForeignKey("EstatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortalRRHHFZ.Domain.Entities.Colaborador", "JefeInmediato")
                        .WithMany("Subordinados")
                        .HasForeignKey("JefeInmediatoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PortalRRHHFZ.Domain.Entities.MotivoSalida", "MotivoSalida")
                        .WithMany("Colaboradores")
                        .HasForeignKey("MotivoSalidaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PortalRRHHFZ.Domain.Entities.TipoContrato", "TipoContrato")
                        .WithMany("Colaboradores")
                        .HasForeignKey("TipoContratoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Departamento");

                    b.Navigation("Empresa");

                    b.Navigation("Estatus");

                    b.Navigation("JefeInmediato");

                    b.Navigation("MotivoSalida");

                    b.Navigation("TipoContrato");
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.Departamento", b =>
                {
                    b.HasOne("PortalRRHHFZ.Domain.Entities.Empresa", "Empresa")
                        .WithMany("Departamentos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.DocumentoColaborador", b =>
                {
                    b.HasOne("PortalRRHHFZ.Domain.Entities.Colaborador", "Colaborador")
                        .WithMany("Documentos")
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortalRRHHFZ.Domain.Entities.Usuario", "UsuarioSubio")
                        .WithMany("DocumentosSubidos")
                        .HasForeignKey("SubidoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortalRRHHFZ.Domain.Entities.TipoDocumento", "TipoDocumento")
                        .WithMany("Documentos")
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Colaborador");

                    b.Navigation("TipoDocumento");

                    b.Navigation("UsuarioSubio");
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.HistorialColaborador", b =>
                {
                    b.HasOne("PortalRRHHFZ.Domain.Entities.Colaborador", "Colaborador")
                        .WithMany("Historiales")
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortalRRHHFZ.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Historiales")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Colaborador");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.RequisicionPersonal", b =>
                {
                    b.HasOne("PortalRRHHFZ.Domain.Entities.Colaborador", "ColaboradorReemplazado")
                        .WithMany()
                        .HasForeignKey("ColaboradorReemplazadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PortalRRHHFZ.Domain.Entities.Departamento", "DepartamentoSolicitado")
                        .WithMany()
                        .HasForeignKey("DepartamentoSolicitadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PortalRRHHFZ.Domain.Entities.Solicitud", "Solicitud")
                        .WithOne("RequisicionPersonal")
                        .HasForeignKey("PortalRRHHFZ.Domain.Entities.RequisicionPersonal", "SolicitudId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortalRRHHFZ.Domain.Entities.TipoContrato", "TipoContrato")
                        .WithMany()
                        .HasForeignKey("TipoContratoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ColaboradorReemplazado");

                    b.Navigation("DepartamentoSolicitado");

                    b.Navigation("Solicitud");

                    b.Navigation("TipoContrato");
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.Solicitud", b =>
                {
                    b.HasOne("PortalRRHHFZ.Domain.Entities.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PortalRRHHFZ.Domain.Entities.Colaborador", "Colaborador")
                        .WithMany()
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PortalRRHHFZ.Domain.Entities.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PortalRRHHFZ.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PortalRRHHFZ.Domain.Entities.Usuario", "SolicitanteUsuario")
                        .WithMany()
                        .HasForeignKey("SolicitanteUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Colaborador");

                    b.Navigation("Departamento");

                    b.Navigation("Empresa");

                    b.Navigation("SolicitanteUsuario");
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.SolicitudAprobacion", b =>
                {
                    b.HasOne("PortalRRHHFZ.Domain.Entities.Solicitud", "Solicitud")
                        .WithMany("Aprobaciones")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortalRRHHFZ.Domain.Entities.Usuario", "UsuarioAprobador")
                        .WithMany()
                        .HasForeignKey("UsuarioAprobadorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Solicitud");

                    b.Navigation("UsuarioAprobador");
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.SolicitudHistorial", b =>
                {
                    b.HasOne("PortalRRHHFZ.Domain.Entities.Solicitud", "Solicitud")
                        .WithMany("Historial")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortalRRHHFZ.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Solicitud");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("PortalRRHHFZ.Domain.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.Cargo", b =>
                {
                    b.Navigation("Colaboradores");
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.Colaborador", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Documentos");

                    b.Navigation("Historiales");

                    b.Navigation("Subordinados");
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.Departamento", b =>
                {
                    b.Navigation("Cargos");

                    b.Navigation("Colaboradores");
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.DocumentoColaborador", b =>
                {
                    b.Navigation("Alertas");
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.Empresa", b =>
                {
                    b.Navigation("Colaboradores");

                    b.Navigation("Departamentos");
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.EstatusColaborador", b =>
                {
                    b.Navigation("Colaboradores");
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.MotivoSalida", b =>
                {
                    b.Navigation("Colaboradores");
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.Solicitud", b =>
                {
                    b.Navigation("Aprobaciones");

                    b.Navigation("Historial");

                    b.Navigation("RequisicionPersonal");
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.TipoContrato", b =>
                {
                    b.Navigation("Colaboradores");
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.TipoDocumento", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("PortalRRHHFZ.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("AlertasGestionadas");

                    b.Navigation("DocumentosSubidos");

                    b.Navigation("Historiales");
                });
#pragma warning restore 612, 618
        }
    }
}
